// Map outline generated by tools/make_map.py - do not edit by hand
// source: ne_10m_coastline.geojson, ne_10m_admin_0_boundary_lines_land.geojson, ne_10m_admin_1_states_provinces_lines.geojson
// center 39.2029,-94.6421  radius 15 km  tol 0.0020 deg  24 points
// format: lat,lon pairs; NAN,NAN = polyline separator
#pragma once
#include <math.h>
inline const float MAP_OUTLINE[] = {
  39.2873f,-94.8790f,39.2691f,-94.8448f,39.2595f,-94.8351f,39.2173f,-94.8296f,39.2077f,-94.8106f,39.2028f,-94.7904f,39.1799f,-94.7462f,39.1729f,-94.7241f,
  NAN,NAN,
  39.1738f,-94.6932f,39.1725f,-94.6782f,
  NAN,NAN,
  39.1729f,-94.7241f,39.1738f,-94.6932f,
  NAN,NAN,
  39.1733f,-94.6681f,39.1699f,-94.6581f,39.1593f,-94.6527f,39.1577f,-94.6289f,39.1528f,-94.6125f,39.1443f,-94.6105f,39.1325f,-94.6246f,39.1245f,-94.6223f,39.1231f,-94.6177f,38.9153f,-94.6177f,
  NAN,NAN,
  39.1725f,-94.6782f,39.1733f,-94.6681f,
  NAN,NAN,
};
static const int MAP_OUTLINE_LEN = sizeof(MAP_OUTLINE)/sizeof(float);
